platform :ios, '8.0'
pod 'SIAlertView', '~> 1.3'
pod 'pop', '~> 1.0.7'
pod 'UITextField+Shake', '~> 0.4'
pod 'FlatUIKit', '~> 1.6'
pod 'Parse', '~> 1.7.4'
pod 'PPRevealSideViewController', '~> 1.2.0'
pod 'RMDateSelectionViewController', '~> 1.5.0'
pod 'HMSegmentedControl', '~> 1.5.1'
