platform :ios, '7.0'
pod 'SIAlertView', '~> 1.3'
pod 'pop', '~> 1.0.7'
pod 'UITextField+Shake', '~> 0.4'
pod 'FlatUIKit', '~> 1.6'
pod 'Parse', '~> 1.7.0'
pod 'PPRevealSideViewController', '~> 1.2.0'
pod 'SVGeocoder', '~> 0.1'
